services:
  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "5266:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Server=db;Port=5436;Database=BWDbManagement;Pooling=true;

  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - "5137:80"

  db:
    image: postgres:latest
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: BWDbManagement
