services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "7131:7131"
    depends_on:
      - server
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    volumes:
      - ./client:/app
    command: ["dotnet", "Client.dll"]

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5065:5065"
    depends_on:
      - database
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "your-connection-string"
    volumes:
      - ./server:/app
    command: ["dotnet", "Server.dll"]
